from __future__ import annotations
import re
import textwrap
from uuid import UUID

from py_vui.lib.codegen.types import WrittenFile
from py_vui.models.nodes import (
    Node,
    NodeType,
    WindowNode,
    FrameNode,
    LabelNode,
    ButtonNode,
    LineEditNode,
    CheckboxNode,
)
from py_vui.models.project import py_vuiProject
from py_vui.models.properties import (
    WindowProperties,
    LabelProperties,
    ButtonProperties,
    LineEditProperties,
    CheckboxProperties,
)


class PySideEmitter:
    supported_widgets: dict[NodeType, tuple[str, str]] = {
        WindowNode.type: ("QWidget", "QWidget()"),
        FrameNode.type: ("QFrame", "QFrame()"),
        LabelNode.type: ("QLabel", "QLabel()"),
        ButtonNode.type: ("QPushButton", "QPushButton()"),
        LineEditNode.type: ("QLineEdit", "QLineEdit()"),
        CheckboxNode.type: ("QCheckBox", "QCheckBox()"),
    }

    def __init__(self, project: py_vuiProject):
        self.project = project

    def _py_ident(self, node_id: UUID) -> str:
        return f"w_{node_id}"

    def _emit_widget_ctor(self, node: Node) -> tuple[str, str]:
        return self.supported_widgets[node.type]

    def _handle_window_properties(
        self, node_properties: WindowProperties, property: str
    ) -> list[str]:
        properties: list[str] = []
        properties.append(f"{property}.setWindowTitle({node_properties.title!r})")
        properties.append(
            f"{property}.resize(int({node_properties.width}), int({node_properties.height}))"
        )
        return properties

    def _handle_label_properties(
        self, node_properties: LabelProperties, property: str
    ) -> list[str]:
        properties: list[str] = []
        properties.append(f"{property}.setText({node_properties.text!r})")
        return properties

    def _handle_button_properties(
        self, node_properties: ButtonProperties, property: str
    ) -> list[str]:
        properties: list[str] = []
        properties.append(f"{property}.setText({node_properties.text!r})")
        return properties

    def _handle_line_edit_properties(
        self, node_properties: LineEditProperties, property: str
    ) -> list[str]:
        properties: list[str] = []
        properties.append(f"{property}.setText({node_properties.text!r})")
        properties.append(
            f"{property}.setPlaceholderText({node_properties.placeholder!r})"
        )
        return properties

    def _handle_checkbox_properties(
        self, node_properties: CheckboxProperties, property: str
    ) -> list[str]:
        properties: list[str] = []
        properties.append(f"{property}.setText({node_properties.text!r})")
        properties.append(f"{property}.setChecked({str(node_properties.checked)})")
        return properties

    def _emit_property_lines(self, node: Node, property: str) -> list[str]:
        properties: list[str] = []
        layout_box = node.layout.box
        properties.append(
            f"{property}.setGeometry(int({layout_box.x}), int({layout_box.y}), int({layout_box.width}), int({layout_box.height}))"
        )
        node_properties = node.properties
        match node_properties:
            case WindowProperties():
                properties.extend(
                    self._handle_window_properties(node_properties, property)
                )
            case LabelProperties():
                properties.extend(
                    self._handle_label_properties(node_properties, property)
                )
            case ButtonProperties():
                properties.extend(
                    self._handle_button_properties(node_properties, property)
                )
            case LineEditProperties():
                properties.extend(
                    self._handle_line_edit_properties(node_properties, property)
                )
            case CheckboxProperties():
                properties.extend(
                    self._handle_checkbox_properties(node_properties, property)
                )
            case _:
                msg = f"unsupported node type for PySide6 emit: {node.type!r}"
                raise ValueError(msg)
        return properties

    def depth_first_search(self, project: py_vuiProject, node: Node) -> list[Node]:
        order: list[Node] = []
        order.append(node)
        for child in project.get_children(node.id):
            order.extend(self.depth_first_search(project, child))
        return order

    def get_header_template(self) -> str:
        return """Generated by py_vui — do not hand-edit unless you know the merge rules.
        
        def build_ui():
            from PySide6.QtWidgets import (
            """

    def get_imports_template(self, imports: list[str]) -> str:
        import_list = [f"        {_import}," for _import in imports]
        import_string = "\n".join(import_list)
        return f"""{import_string}
            )
        """

    def get_body_template(self, nodes: list[str]) -> str:
        nodes_list = [f"    {node}" for node in nodes]
        nodes_string = "\n".join(nodes_list)
        return f"""{nodes_string}
        """

    def emit_pyside_phase1(self, project: py_vuiProject) -> list[WrittenFile]:
        node = project.get_node(project.root_id)
        order = self.depth_first_search(project, node)

        imports: set[str] = set()
        body: list[str] = []
        for node in order:
            _import, ctor = self._emit_widget_ctor(node)
            imports.add(_import)
            indent = self._py_ident(node.id)
            body.append(f"{indent} = {ctor}")
            if node.id != project.root_id and node.parent_id is not None:
                parent = project.get_node(node.parent_id)
                parent_indent = self._py_ident(parent.id)
                body.append(f"{indent}.setParent({parent_indent})")
            body.extend(self._emit_property_lines(node, indent))

        root_indent = self._py_ident(project.root_id)
        body.append(f"return {root_indent}")

        header_template = self.get_header_template()
        header_imports_template = self.get_imports_template(sorted(imports))
        body_template = self.get_body_template(body)

        ui_text = f"""{header_template}
        
        {header_imports_template}
        
        {body_template}
        """

        main_text = textwrap.dedent(
            """\
            import sys

            from PySide6.QtWidgets import QApplication

            from ui_generated import build_ui


            def main() -> int:
                app = QApplication(sys.argv)
                root = build_ui()
                root.show()
                return int(app.exec())


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        )

        return [
            WrittenFile(
                path="generated/ui_generated.py",
                content=ui_text,
            ),
            WrittenFile(
                path="generated/main.py",
                content=main_text,
            ),
        ]
