from __future__ import annotations

import re
import sys
import textwrap

from py_vui.codegen.types import WrittenFile
from py_vui.model.document import ProjectDocument
from py_vui.model.nodes import (
    ButtonNode,
    CheckboxNode,
    FrameNode,
    LabelNode,
    LineEditNode,
    Node,
    WindowNode,
)
from py_vui.model.project import py_vuiProject

_MIN_PYTHON = f"{sys.version_info.major}.{sys.version_info.minor}"


def _py_ident(node_id: str) -> str:
    return "w_" + re.sub(r"[^0-9a-zA-Z]+", "_", node_id)


def _emit_widget_ctor(node: Node) -> tuple[str, str]:
    if isinstance(node, WindowNode):
        return ("QWidget", "QWidget()")
    if isinstance(node, FrameNode):
        return ("QFrame", "QFrame()")
    if isinstance(node, LabelNode):
        return ("QLabel", "QLabel()")
    if isinstance(node, ButtonNode):
        return ("QPushButton", "QPushButton()")
    if isinstance(node, LineEditNode):
        return ("QLineEdit", "QLineEdit()")
    if isinstance(node, CheckboxNode):
        return ("QCheckBox", "QCheckBox()")
    msg = f"unsupported node type for Phase 1 PySide6 emit: {node.type!r}"
    raise ValueError(msg)


def _emit_props_lines(node: Node, var: str) -> list[str]:
    lines: list[str] = []
    b = node.layout.box
    lines.append(f"{var}.setGeometry(int({b.x}), int({b.y}), int({b.w}), int({b.h}))")
    if isinstance(node, WindowNode):
        p = node.props
        lines.append(f"{var}.setWindowTitle({p.title!r})")
        lines.append(f"{var}.resize(int({p.width}), int({p.height}))")
    elif isinstance(node, LabelNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, ButtonNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, LineEditNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setPlaceholderText({node.props.placeholder!r})")
    elif isinstance(node, CheckboxNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setChecked({str(node.props.checked)})")
    return lines


def _emit_ui_module(project: py_vuiProject) -> str:
    doc = ProjectDocument(project)
    order: list[str] = []

    def dfs(nid: str) -> None:
        order.append(nid)
        for ch in doc.children(nid):
            dfs(ch.id)

    dfs(project.root_id)

    imports: set[str] = set()
    body: list[str] = []
    for nid in order:
        node = project.nodes[nid]
        imp, ctor = _emit_widget_ctor(node)
        imports.add(imp)
        var = _py_ident(nid)
        body.append(f"{var} = {ctor}")

    for nid in order:
        node = project.nodes[nid]
        var = _py_ident(nid)
        if nid != project.root_id and node.parent_id is not None:
            parent = project.nodes[node.parent_id]
            pvar = _py_ident(parent.id)
            body.append(f"{var}.setParent({pvar})")
        body.extend(_emit_props_lines(node, var))

    root_var = _py_ident(project.root_id)
    body.append(f"return {root_var}")

    ui_lines: list[str] = [
        '"""UI layout generated by py_vui."""',
        "",
        "def build_ui():",
        "    from PySide6.QtWidgets import (",
    ]
    for name in sorted(imports):
        ui_lines.append(f"        {name},")
    ui_lines.append("    )")
    ui_lines.append("")
    for ln in body:
        ui_lines.append(f"    {ln}")
    return "\n".join(ui_lines) + "\n"


def _emit_main_module(project_name: str) -> str:
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        \"\"\"Runnable desktop app generated by py_vui.\"\"\"
        from __future__ import annotations

        import sys
        from pathlib import Path

        APP_DIR = Path(__file__).resolve().parent
        if str(APP_DIR) not in sys.path:
            sys.path.insert(0, str(APP_DIR))


        def _require_pyside6() -> None:
            try:
                import PySide6  # noqa: F401
            except ModuleNotFoundError as exc:
                print("PySide6 is not installed for this Python interpreter.")
                print(f"  Python: {{sys.executable}}")
                print()
                print("Install dependencies, then run again:")
                print(f"  cd {{APP_DIR}}")
                print("  pip install -r requirements.txt")
                print("  python main.py")
                raise SystemExit(1) from exc


        def main() -> int:
            _require_pyside6()
            from PySide6.QtWidgets import QApplication

            from ui_generated import build_ui

            app = QApplication(sys.argv)
            app.setApplicationName({project_name!r})
            root = build_ui()
            root.show()
            return int(app.exec())


        if __name__ == "__main__":
            raise SystemExit(main())
        """
    )


def _emit_requirements() -> str:
    return "PySide6>=6.6\n"


def _emit_readme(project_name: str) -> str:
    return textwrap.dedent(
        f"""\
        # {project_name}

        Desktop app generated by [py_vui](https://github.com/dfunani/py_vui).

        ## Requirements

        - Python {_MIN_PYTHON}+
        - PySide6

        ## Run

        ```bash
        cd "$(dirname "$0")"
        python3 -m venv .venv
        source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
        pip install -r requirements.txt
        python main.py
        ```

        Or, if PySide6 is already installed globally:

        ```bash
        python main.py
        ```
        """
    )


def emit_pyside_phase1(project: py_vuiProject) -> list[WrittenFile]:
    if project.adapter != "pyside6":
        msg = f"unsupported adapter {project.adapter!r}"
        raise ValueError(msg)

    name = project.meta.name
    return [
        WrittenFile("ui_generated.py", _emit_ui_module(project)),
        WrittenFile("main.py", _emit_main_module(name)),
        WrittenFile("requirements.txt", _emit_requirements()),
        WrittenFile("README.md", _emit_readme(name)),
    ]
