from __future__ import annotations

import re
import sys
import textwrap

from py_vui.codegen.types import WrittenFile
from py_vui.model.document import ProjectDocument
from py_vui.model.interaction import HandlerDef
from py_vui.model.nodes import (
    ButtonNode,
    CheckboxNode,
    FrameNode,
    LabelNode,
    LineEditNode,
    Node,
    WindowNode,
)
from py_vui.model.project import py_vuiProject
from py_vui.model.theme import (
    application_stylesheet,
    stylesheet_for_node,
)

_MIN_PYTHON = f"{sys.version_info.major}.{sys.version_info.minor}"


def _py_ident(node_id: str) -> str:
    return "w_" + re.sub(r"[^0-9a-zA-Z]+", "_", node_id)


def _widget_key(name: str) -> str:
    return re.sub(r"[^0-9a-zA-Z_]+", "_", name.strip()) or "widget"


def _emit_widget_ctor(node: Node) -> tuple[str, str]:
    if isinstance(node, WindowNode):
        return ("QWidget", "QWidget()")
    if isinstance(node, FrameNode):
        return ("QFrame", "QFrame()")
    if isinstance(node, LabelNode):
        return ("QLabel", "QLabel()")
    if isinstance(node, ButtonNode):
        return ("QPushButton", "QPushButton()")
    if isinstance(node, LineEditNode):
        return ("QLineEdit", "QLineEdit()")
    if isinstance(node, CheckboxNode):
        return ("QCheckBox", "QCheckBox()")
    msg = f"unsupported node type for Phase 1 PySide6 emit: {node.type!r}"
    raise ValueError(msg)


def _emit_props_lines(project: py_vuiProject, node: Node, var: str) -> list[str]:
    theme = project.theme
    lines: list[str] = []
    b = node.layout.box
    lines.append(f"{var}.setGeometry(int({b.x}), int({b.y}), int({b.w}), int({b.h}))")
    if not node.enabled:
        lines.append(f"{var}.setEnabled(False)")
    qss = stylesheet_for_node(theme=theme, node_type=node.type, style=node.style)
    if qss:
        lines.append(f"{var}.setStyleSheet({qss!r})")
    if isinstance(node, WindowNode):
        p = node.props
        lines.append(f"{var}.setWindowTitle({p.title!r})")
        lines.append(f"{var}.resize(int({p.width}), int({p.height}))")
    elif isinstance(node, LabelNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, ButtonNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, LineEditNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setPlaceholderText({node.props.placeholder!r})")
    elif isinstance(node, CheckboxNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setChecked({str(node.props.checked)})")
    return lines


def _emit_ui_module(project: py_vuiProject) -> str:
    doc = ProjectDocument(project)
    order: list[str] = []

    def dfs(nid: str) -> None:
        order.append(nid)
        for ch in doc.children(nid):
            dfs(ch.id)

    dfs(project.root_id)

    imports: set[str] = set()
    body: list[str] = []
    widget_entries: list[str] = []
    for nid in order:
        node = project.nodes[nid]
        imp, ctor = _emit_widget_ctor(node)
        imports.add(imp)
        var = _py_ident(nid)
        body.append(f"{var} = {ctor}")
        widget_entries.append(f'    "{_widget_key(node.name)}": {var},')

    for nid in order:
        node = project.nodes[nid]
        var = _py_ident(nid)
        if nid != project.root_id and node.parent_id is not None:
            parent = project.nodes[node.parent_id]
            pvar = _py_ident(parent.id)
            body.append(f"{var}.setParent({pvar})")
        body.extend(_emit_props_lines(project, node, var))

    root_var = _py_ident(project.root_id)
    body.append("WIDGETS = {")
    body.extend(widget_entries)
    body.append("}")
    body.append(f"return {root_var}")

    ui_lines: list[str] = [
        '"""UI layout generated by py_vui."""',
        "",
        "WIDGETS: dict = {}",
        "",
        "def build_ui():",
        "    global WIDGETS",
        "    from PySide6.QtWidgets import (",
    ]
    for name in sorted(imports):
        ui_lines.append(f"        {name},")
    ui_lines.append("    )")
    ui_lines.append("")
    for ln in body:
        ui_lines.append(f"    {ln}")
    return "\n".join(ui_lines) + "\n"


def _indent_body(body: str) -> str:
    lines = body.strip().splitlines() or ["pass"]
    return "\n".join("    " + ln if ln.strip() else "    pass" for ln in lines)


def _emit_handlers_module(handlers: dict[str, HandlerDef]) -> str:
    lines = [
        '"""Event handlers generated by py_vui — edit the function bodies."""',
        "from __future__ import annotations",
        "",
    ]
    if not handlers:
        lines.append("# No handlers yet. Assign actions to buttons in the editor.")
        lines.append("")
        return "\n".join(lines) + "\n"

    for handler in handlers.values():
        lines.append(f"def {handler.name}() -> None:")
        lines.append(_indent_body(handler.body))
        lines.append("")
    return "\n".join(lines)


def _emit_interactions_module(project: py_vuiProject) -> str:
    lines = [
        '"""Signal wiring generated by py_vui."""',
        "from __future__ import annotations",
        "",
        "from PySide6.QtWidgets import QLineEdit",
        "",
        "from handlers import (",
    ]
    handler_names: set[str] = set()
    wires: list[str] = []

    for node in project.nodes.values():
        key = _widget_key(node.name)
        var = f'WIDGETS[{key!r}]'
        if isinstance(node, ButtonNode) and node.props.on_click:
            handler_names.add(node.props.on_click)
            wires.append(f"    {var}.clicked.connect({node.props.on_click})")
        elif isinstance(node, LineEditNode) and node.props.on_return:
            handler_names.add(node.props.on_return)
            wires.append(
                f"    {var}.returnPressed.connect({node.props.on_return})"
            )
        elif isinstance(node, CheckboxNode) and node.props.on_toggle:
            handler_names.add(node.props.on_toggle)
            wires.append(f"    {var}.toggled.connect({node.props.on_toggle})")

    if handler_names:
        for name in sorted(handler_names):
            lines.append(f"    {name},")
    else:
        lines.append("    # no handlers")
    lines.append(")")
    lines.append("from ui_generated import WIDGETS")
    lines.append("")
    lines.append("")
    lines.append("def wire_handlers() -> None:")
    if not wires:
        lines.append("    return")
    else:
        for wire in wires:
            lines.append(wire)
    lines.append("")
    return "\n".join(lines)


def _emit_theme_module(project: py_vuiProject) -> str:
    t = project.theme
    return textwrap.dedent(
        f"""\
        \"\"\"Application theme generated by py_vui.\"\"\"
        from __future__ import annotations

        THEME = {{
            "preset": {t.preset!r},
            "font_family": {t.font_family!r},
            "font_size": {t.font_size},
            "primary": {t.primary!r},
            "background": {t.background!r},
            "surface": {t.surface!r},
            "text": {t.text!r},
            "button_text": {t.button_text!r},
            "button_radius": {t.button_radius},
            "border": {t.border!r},
        }}


        def apply_theme(app) -> None:
            app.setStyleSheet({application_stylesheet(t)!r})
        """
    )


def _emit_main_module(project_name: str, *, has_handlers: bool) -> str:
    wire_lines = (
        [
            "    from interactions import wire_handlers",
            "    wire_handlers()",
        ]
        if has_handlers
        else []
    )
    wire_block = "\n".join(wire_lines) + ("\n" if wire_lines else "")
    return textwrap.dedent(
        f"""\
        #!/usr/bin/env python3
        \"\"\"Runnable desktop app generated by py_vui.\"\"\"
        from __future__ import annotations

        import sys
        from pathlib import Path

        APP_DIR = Path(__file__).resolve().parent
        if str(APP_DIR) not in sys.path:
            sys.path.insert(0, str(APP_DIR))


        def _require_pyside6() -> None:
            try:
                import PySide6  # noqa: F401
            except ModuleNotFoundError as exc:
                print("PySide6 is not installed for this Python interpreter.")
                print(f"  Python: {{sys.executable}}")
                print()
                print("Install dependencies, then run again:")
                print(f"  cd {{APP_DIR}}")
                print("  pip install -r requirements.txt")
                print("  python main.py")
                raise SystemExit(1) from exc


        def main() -> int:
            _require_pyside6()
            from PySide6.QtWidgets import QApplication

            from theme import apply_theme
            from ui_generated import build_ui

            app = QApplication(sys.argv)
            app.setApplicationName({project_name!r})
            apply_theme(app)
            root = build_ui()
        {wire_block}    root.show()
            return int(app.exec())


        if __name__ == "__main__":
            raise SystemExit(main())
        """
    )


def _emit_requirements() -> str:
    return "PySide6>=6.6\n"


def _emit_readme(project_name: str) -> str:
    return textwrap.dedent(
        f"""\
        # {project_name}

        Desktop app generated by [py_vui](https://github.com/dfunani/py_vui).

        ## Requirements

        - Python {_MIN_PYTHON}+
        - PySide6

        ## Run

        ```bash
        cd "$(dirname "$0")"
        python3 -m venv .venv
        source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
        pip install -r requirements.txt
        python main.py
        ```

        ## Customize

        - **Theme:** edit `theme.py` or re-export from py_vui with a different preset.
        - **Handlers:** edit function bodies in `handlers.py` (wired in `interactions.py`).
        - **Layout:** regenerate from py_vui; hand-edits in `ui_generated.py` may be overwritten.
        """
    )


def _project_has_handlers(project: py_vuiProject) -> bool:
    for node in project.nodes.values():
        if isinstance(node, ButtonNode) and node.props.on_click:
            return True
        if isinstance(node, LineEditNode) and node.props.on_return:
            return True
        if isinstance(node, CheckboxNode) and node.props.on_toggle:
            return True
    return False


def emit_pyside_phase1(project: py_vuiProject) -> list[WrittenFile]:
    if project.adapter != "pyside6":
        msg = f"unsupported adapter {project.adapter!r}"
        raise ValueError(msg)

    name = project.meta.name
    has_handlers = _project_has_handlers(project)
    files = [
        WrittenFile("ui_generated.py", _emit_ui_module(project)),
        WrittenFile("theme.py", _emit_theme_module(project)),
        WrittenFile("handlers.py", _emit_handlers_module(project.handlers)),
        WrittenFile("interactions.py", _emit_interactions_module(project)),
        WrittenFile(
            "main.py",
            _emit_main_module(name, has_handlers=has_handlers),
        ),
        WrittenFile("requirements.txt", _emit_requirements()),
        WrittenFile("README.md", _emit_readme(name)),
    ]
    return files
