from __future__ import annotations

import re
import textwrap

from py_vui.codegen.types import WrittenFile
from py_vui.model.document import ProjectDocument
from py_vui.model.nodes import (
    ButtonNode,
    CheckboxNode,
    FrameNode,
    LabelNode,
    LineEditNode,
    Node,
    WindowNode,
)
from py_vui.model.project import py_vuiProject


def _py_ident(node_id: str) -> str:
    return "w_" + re.sub(r"[^0-9a-zA-Z]+", "_", node_id)


def _emit_widget_ctor(node: Node) -> tuple[str, str]:
    if isinstance(node, WindowNode):
        return ("QWidget", "QWidget()")
    if isinstance(node, FrameNode):
        return ("QFrame", "QFrame()")
    if isinstance(node, LabelNode):
        return ("QLabel", "QLabel()")
    if isinstance(node, ButtonNode):
        return ("QPushButton", "QPushButton()")
    if isinstance(node, LineEditNode):
        return ("QLineEdit", "QLineEdit()")
    if isinstance(node, CheckboxNode):
        return ("QCheckBox", "QCheckBox()")
    msg = f"unsupported node type for Phase 1 PySide6 emit: {node.type!r}"
    raise ValueError(msg)


def _emit_props_lines(node: Node, var: str) -> list[str]:
    lines: list[str] = []
    b = node.layout.box
    lines.append(f"{var}.setGeometry(int({b.x}), int({b.y}), int({b.w}), int({b.h}))")
    if isinstance(node, WindowNode):
        p = node.props
        lines.append(f"{var}.setWindowTitle({p.title!r})")
        lines.append(f"{var}.resize(int({p.width}), int({p.height}))")
    elif isinstance(node, LabelNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, ButtonNode):
        lines.append(f"{var}.setText({node.props.text!r})")
    elif isinstance(node, LineEditNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setPlaceholderText({node.props.placeholder!r})")
    elif isinstance(node, CheckboxNode):
        lines.append(f"{var}.setText({node.props.text!r})")
        lines.append(f"{var}.setChecked({str(node.props.checked)})")
    return lines


def emit_pyside_phase1(project: py_vuiProject) -> list[WrittenFile]:
    if project.adapter != "pyside6":
        msg = f"unsupported adapter {project.adapter!r}"
        raise ValueError(msg)

    doc = ProjectDocument(project)
    order: list[str] = []

    def dfs(nid: str) -> None:
        order.append(nid)
        for ch in doc.children(nid):
            dfs(ch.id)

    dfs(project.root_id)

    imports: set[str] = set()
    body: list[str] = []
    for nid in order:
        node = project.nodes[nid]
        imp, ctor = _emit_widget_ctor(node)
        imports.add(imp)
        var = _py_ident(nid)
        body.append(f"{var} = {ctor}")

    for nid in order:
        node = project.nodes[nid]
        var = _py_ident(nid)
        if nid != project.root_id and node.parent_id is not None:
            parent = project.nodes[node.parent_id]
            pvar = _py_ident(parent.id)
            body.append(f"{var}.setParent({pvar})")
        body.extend(_emit_props_lines(node, var))

    root_var = _py_ident(project.root_id)
    body.append(f"return {root_var}")

    import_names = sorted(imports)
    ui_lines: list[str] = [
        '"""Generated by py_vui — do not hand-edit unless you know the merge rules."""',
        "",
        "def build_ui():",
        "    from PySide6.QtWidgets import (",
    ]
    for name in import_names:
        ui_lines.append(f"        {name},")
    ui_lines.append("    )")
    ui_lines.append("")
    for ln in body:
        ui_lines.append(f"    {ln}")
    ui_text = "\n".join(ui_lines) + "\n"

    main_text = textwrap.dedent(
        """\
        import sys

        from PySide6.QtWidgets import QApplication

        from ui_generated import build_ui


        def main() -> int:
            app = QApplication(sys.argv)
            root = build_ui()
            root.show()
            return int(app.exec())


        if __name__ == "__main__":
            raise SystemExit(main())
        """
    )

    return [
        WrittenFile("generated/ui_generated.py", ui_text),
        WrittenFile("generated/main.py", main_text),
    ]
